<?php

/**
 * Implements hook_theme().
 */
function kenny_core_theme($existing, $type, $theme, $path):array {
  return [
    'kenny_social_media_bar' => [
      'variables' => []
    ],
    'kenny_social_media_black_bar' => [
      'variables' => []
    ],
    'kenny_social_media_bar_mobile' => [
      'variables' => []
    ],
    'kenny_social_share_this' => [
      'variables' => []
    ],
    'kenny_weather_block' => [
      'variables' => [
        'temp' => null,
        'weather_text' => '',
        'city' => '',
        'units' => '',
      ]
    ]
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function kenny_core_theme_suggestions_views_view_alter(array &$suggestions, array &$variables):void {
  $suggestions[] = 'views_view__' . $variables['view']->id();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function kenny_core_theme_suggestions_views_mini_pager_alter(array &$suggestions, array &$variables):void {
  $route_name = \Drupal::routeMatch()->getRouteName();

  $type = 'default';
  if ($route_name == 'entity.node.canonical') {
    $type = 'node';
  }

  if ($route_name == 'entity.taxonomy_term.canonical') {
    $type = 'category';
  }

  $suggestions[] = 'views_mini_pager__' . $type;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function kenny_core_preprocess_node__news__full(&$variables):void {

  // @todo Added a container for two blocks that are in the same action to improve styling.
    $content = $variables['content']['_layout_builder'][1]['content'];

    $arr = [];
    $count = 0;

    foreach ($content as $item) {
      $arr[$count] = $item;
      $count++;
    }

    $container = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['hero_image--container'],
      ],
      'block_hero_text' => $arr[0],
      'block_about_author' => $arr[1],
    ];

    $variables['content']['_layout_builder']['1']['content'] = $container;
}
