<?php

use Drupal\Core\Url;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function kenny_core_theme($existing, $type, $theme, $path) {
  return [
    'kenny_social_media_bar' => [
      'variables' => []
    ],
    'kenny_social_media_black_bar' => [
      'variables' => []
    ],
    'kenny_social_media_bar_mobile' => [
      'variables' => []
    ],
//  'kenny_about_us' => [
//      'variables' => []
//    ],
  ];
}

// @todo Custom code for category hero block. Delete or use later
///**
// * Implements hook_views_pre_view().
// */
//function kenny_core_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
//  if ($view->id() == "category_preview" && $display_id == 'block_category_preview') {
//
//    $current_url = Url::fromRoute('<current>');
//    $current_url_string = $current_url->toString();
//
//    $parts = explode("/", $current_url_string);
//
//    $last_word = end($parts);
//
//    $content_by_category = \Drupal::service('kenny_core.category_content');
//
//    $nid = $content_by_category->getContent($last_word);
//
//
//    $view->setArguments([$nid]);
//    $view->execute();
//  }
//}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function kenny_core_theme_suggestions_views_view_alter(array &$suggestions, array &$variables) {
  $suggestions[] = 'views_view__' . $variables['view']->id();
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function kenny_core_theme_suggestions_views_mini_pager_alter(array &$suggestions, array &$variables) {
  if (!empty($variables['parameters'])) {
    $suggestions[] = 'views_mini_pager__category';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function kenny_core_preprocess_node__news__full(&$variables) {

  // @todo Added a container for two blocks that are in the same action to improve styling.
    $content = $variables['content']['_layout_builder'][1]['content'];

    $arr = [];
    $count = 0;

    foreach ($content as $item) {
      $arr[$count] = $item;
      $count++;
    }

    $container = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['hero_image--container'],
      ],
      'block_hero_text' => $arr[0],
      'block_about_author' => $arr[1],
    ];

    $variables['content']['_layout_builder']['1']['content'] = $container;
}
