<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function global_configuration_theme($existing, $type, $theme, $path):array {
   return [
     'copyrights_block' => [
       'variables' => [
         'text' => NULL,
       ],
     ]
   ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function global_configuration_preprocess_block(&$variables) {

  if ($variables['plugin_id'] == 'menu_social_media_black_bar') {
    $variables['content']['#cache'] = [
      'tags' => ['config_pages:1'],
    ];
  }

}

/**
 * Implements hook_ENTITY_TYPE_presave() for config pages.
 */
function global_configuration_config_pages_presave(EntityInterface $entity){

  if ($entity->bundle() == 'global_configurations') {
    $old_copyright = $entity->original->get('field_copyrights')->value;
    $new_copyright = $entity->get('field_copyrights')->value;

    if ($new_copyright != $old_copyright) {
      \Drupal::service('cache_tags.invalidator')
        ->invalidateTags(['global_configurations']);
    }

  }
}
