kenny_core.weather_settings:
  type: config_object
  label: 'Kenny Core Weather Settings'
  mapping:
    city:
      type: string
      label: 'City'
    units:
      type: string
      label: 'Units'
    appid:
      type: string
      label: 'Key for api'
