ckeditor5.plugin.ckeditor_plugin_button:
  type: mapping
  label: Background color
  mapping:
    enabled_colors:
      type: sequence
      orderby: value
      label: 'Enabled Colors'
      constraints:
        NotBlank:
          message: "Enable at least one color, otherwise disable the button."
      sequence:
        type: string
        label: 'Color types'
        constraints:
          Choice:
            - blue
            - black
            - gray
            - white
            - gold
    enabled_background_colors:
      type: sequence
      orderby: value
      label: 'Enabled Background Colors'
      constraints:
        NotBlank:
          message: "Enable at least one background color, otherwise disable the button."
      sequence:
        type: string
        label: 'Background color types'
        constraints:
          Choice:
            - blue
            - black
            - gray
            - white
            - gold
    default_color:
      type: string
      label: 'Default color'
      constraints:
        Choice:
          - blue
          - black
          - gray
          - white
          - gold
    default_background_color:
      type: string
      label: 'Default background color'
      constraints:
        Choice:
          - blue
          - black
          - gray
          - white
          - gold

